{
    "name": "F&B Core",
    "summary": "Core master data, approval and traceability workflows for the F&B ERP portfolio project",
    "version": "18.0.1.3.4",
    "category": "Operations/Inventory",
    "license": "LGPL-3",
    "author": "Kim Thu",
    "depends": ["base", "product", "stock", "product_expiry", "purchase"],
    "data": [
        "security/fnb_security.xml",
        "security/ir.model.access.csv",
        "data/warehouse_demo.xml",
        "data/product_demo.xml",
        "views/product_template_views.xml",
        "views/fnb_menu_views.xml",
        "views/purchase_rejection_wizard_views.xml",
        "views/purchase_order_views.xml",
    ],
    "installable": True,
    "application": True,
}
